//
//  BotsFactory.swift
//  MySampleApp
//
//
// Copyright 2017 Amazon.com, Inc. or its affiliates (Amazon). All Rights Reserved.
//
// Code generated by AWS Mobile Hub. Amazon gives unlimited permission to 
// copy, distribute and modify it.
//
// Source code generated from template: aws-my-sample-app-ios-swift v0.16
//
import Foundation

/// Manages list of bots available for Demo in the sample app
class BotsFactory {
    // Returns the list of bots configured through Mobile Hub Console
    static var supportedBots: [Bot] {
        return [
            Bot(name: "BookTrip",
                description: "Bot to make reservations necessary for a visit to a city",
                commandsHelp: [
                   ],

                configuration: BotConfiguration(
                    name: BookTripBotName,
                    alias: BookTripBotAlias,
                    region: BookTripBotRegion)),
        ]
    }
}
